title: DALAI-FIN
description: Blog for DALAI-FIN.
show_downloads: true

baseurl: "/" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://dalai-fin.github.io" # change this to the base hostname & protocol for your site



languages: ["en", "fi"]
default_lang: "en"
exclude_from_localization: ["assets/css", "assets/img"]
parallel_localization: true


google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
post:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: lorepirri
image: /thumbnail-jumbo.png
twitter:
  username: lorepirri

plugins:
  - jekyll-target-blank
  - jekyll-polyglot
  - kramdown-parser-gfm

target-blank:
    rel: nofollow

header_page_refs: ['now', 'about', 'contact']
