title: DALAI-FIN
description: Blog for DALAI-FIN.
show_downloads: true

baseurl: "/" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://dalai-fin.github.io" # change this to the base hostname & protocol for your site


defaults:
- scope:
    path: '_posts/en'
  values:
    permalink: 'post/en/:title'
    language: en
- scope:
    path: '_posts/fi'
  values:
    permalink: 'post/fi/:title'
    language: fi


google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
post:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: lorepirri
image: /thumbnail-jumbo.png
twitter:
  username: lorepirri

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['now', 'about', 'contact']
